# Form implementation generated from reading ui file 'ui\channel.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Channel(object):
    def setupUi(self, Channel):
        Channel.setObjectName("Channel")
        Channel.resize(400, 123)
        self.gridLayout = QtWidgets.QGridLayout(Channel)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Channel)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.txtNodeKey = QtWidgets.QLineEdit(Channel)
        self.txtNodeKey.setObjectName("txtNodeKey")
        self.gridLayout.addWidget(self.txtNodeKey, 0, 1, 1, 3)
        self.label_2 = QtWidgets.QLabel(Channel)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.txtLocalAmount = QtWidgets.QLineEdit(Channel)
        self.txtLocalAmount.setObjectName("txtLocalAmount")
        self.gridLayout.addWidget(self.txtLocalAmount, 1, 1, 1, 3)
        self.label_3 = QtWidgets.QLabel(Channel)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.txtRemoteAmount = QtWidgets.QLineEdit(Channel)
        self.txtRemoteAmount.setObjectName("txtRemoteAmount")
        self.gridLayout.addWidget(self.txtRemoteAmount, 2, 1, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(191, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 2)
        self.pbChannel = QtWidgets.QPushButton(Channel)
        self.pbChannel.setObjectName("pbChannel")
        self.gridLayout.addWidget(self.pbChannel, 3, 2, 1, 1)
        self.pbCancelChannel = QtWidgets.QPushButton(Channel)
        self.pbCancelChannel.setObjectName("pbCancelChannel")
        self.gridLayout.addWidget(self.pbCancelChannel, 3, 3, 1, 1)

        self.retranslateUi(Channel)
        QtCore.QMetaObject.connectSlotsByName(Channel)

    def retranslateUi(self, Channel):
        _translate = QtCore.QCoreApplication.translate
        Channel.setWindowTitle(_translate("Channel", "Form"))
        self.label.setText(_translate("Channel", "Node key:"))
        self.label_2.setText(_translate("Channel", "Local Amount:"))
        self.label_3.setText(_translate("Channel", "Remote Amount:"))
        self.pbChannel.setText(_translate("Channel", "Open Channel"))
        self.pbCancelChannel.setText(_translate("Channel", "Cancel"))
