# Form implementation generated from reading ui file 'ui\connect.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Connect(object):
    def setupUi(self, Connect):
        Connect.setObjectName("Connect")
        Connect.resize(399, 69)
        self.gridLayout = QtWidgets.QGridLayout(Connect)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Connect)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.txtNodeUrl = QtWidgets.QLineEdit(Connect)
        self.txtNodeUrl.setObjectName("txtNodeUrl")
        self.gridLayout.addWidget(self.txtNodeUrl, 0, 1, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(185, 21, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 2)
        self.pbConnect = QtWidgets.QPushButton(Connect)
        self.pbConnect.setObjectName("pbConnect")
        self.gridLayout.addWidget(self.pbConnect, 1, 2, 1, 1)
        self.pbCancelConnect = QtWidgets.QPushButton(Connect)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbCancelConnect.sizePolicy().hasHeightForWidth())
        self.pbCancelConnect.setSizePolicy(sizePolicy)
        self.pbCancelConnect.setObjectName("pbCancelConnect")
        self.gridLayout.addWidget(self.pbCancelConnect, 1, 3, 1, 1)

        self.retranslateUi(Connect)
        QtCore.QMetaObject.connectSlotsByName(Connect)

    def retranslateUi(self, Connect):
        _translate = QtCore.QCoreApplication.translate
        Connect.setWindowTitle(_translate("Connect", "Form"))
        self.label.setText(_translate("Connect", "Node Url:"))
        self.txtNodeUrl.setPlaceholderText(_translate("Connect", "Url..."))
        self.pbConnect.setText(_translate("Connect", "Connect"))
        self.pbCancelConnect.setText(_translate("Connect", "Cancel"))
