# Form implementation generated from reading ui file 'ui\create.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Create(object):
    def setupUi(self, Create):
        Create.setObjectName("Create")
        Create.resize(312, 96)
        self.gridLayout = QtWidgets.QGridLayout(Create)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Create)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.txtNameCreate = QtWidgets.QLineEdit(Create)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtNameCreate.sizePolicy().hasHeightForWidth())
        self.txtNameCreate.setSizePolicy(sizePolicy)
        self.txtNameCreate.setObjectName("txtNameCreate")
        self.gridLayout.addWidget(self.txtNameCreate, 0, 1, 1, 3)
        self.label_2 = QtWidgets.QLabel(Create)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.txtPasswordCreate = QtWidgets.QLineEdit(Create)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtPasswordCreate.sizePolicy().hasHeightForWidth())
        self.txtPasswordCreate.setSizePolicy(sizePolicy)
        self.txtPasswordCreate.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtPasswordCreate.setObjectName("txtPasswordCreate")
        self.gridLayout.addWidget(self.txtPasswordCreate, 1, 1, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(125, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 2)
        self.pbCreate = QtWidgets.QPushButton(Create)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbCreate.sizePolicy().hasHeightForWidth())
        self.pbCreate.setSizePolicy(sizePolicy)
        self.pbCreate.setObjectName("pbCreate")
        self.gridLayout.addWidget(self.pbCreate, 2, 2, 1, 1)
        self.pbCancelCreate = QtWidgets.QPushButton(Create)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbCancelCreate.sizePolicy().hasHeightForWidth())
        self.pbCancelCreate.setSizePolicy(sizePolicy)
        self.pbCancelCreate.setObjectName("pbCancelCreate")
        self.gridLayout.addWidget(self.pbCancelCreate, 2, 3, 1, 1)

        self.retranslateUi(Create)
        QtCore.QMetaObject.connectSlotsByName(Create)

    def retranslateUi(self, Create):
        _translate = QtCore.QCoreApplication.translate
        Create.setWindowTitle(_translate("Create", "Form"))
        self.label.setText(_translate("Create", "Name:"))
        self.txtNameCreate.setText(_translate("Create", "alice"))
        self.txtNameCreate.setPlaceholderText(_translate("Create", "Name..."))
        self.label_2.setText(_translate("Create", "Password:"))
        self.txtPasswordCreate.setText(_translate("Create", "Santiago1"))
        self.txtPasswordCreate.setPlaceholderText(_translate("Create", "Password..."))
        self.pbCreate.setText(_translate("Create", "Create Wallet"))
        self.pbCancelCreate.setText(_translate("Create", "Cancel"))
