# Form implementation generated from reading ui file 'ui\invoice.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Invoice(object):
    def setupUi(self, Invoice):
        Invoice.setObjectName("Invoice")
        Invoice.resize(400, 69)
        self.gridLayout = QtWidgets.QGridLayout(Invoice)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Invoice)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.txtInvoiceAmount = QtWidgets.QLineEdit(Invoice)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtInvoiceAmount.sizePolicy().hasHeightForWidth())
        self.txtInvoiceAmount.setSizePolicy(sizePolicy)
        self.txtInvoiceAmount.setText("")
        self.txtInvoiceAmount.setPlaceholderText("")
        self.txtInvoiceAmount.setObjectName("txtInvoiceAmount")
        self.gridLayout.addWidget(self.txtInvoiceAmount, 0, 1, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(185, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 2)
        self.pbInvoice = QtWidgets.QPushButton(Invoice)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbInvoice.sizePolicy().hasHeightForWidth())
        self.pbInvoice.setSizePolicy(sizePolicy)
        self.pbInvoice.setObjectName("pbInvoice")
        self.gridLayout.addWidget(self.pbInvoice, 1, 2, 1, 1)
        self.pbCancelInvoice = QtWidgets.QPushButton(Invoice)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbCancelInvoice.sizePolicy().hasHeightForWidth())
        self.pbCancelInvoice.setSizePolicy(sizePolicy)
        self.pbCancelInvoice.setObjectName("pbCancelInvoice")
        self.gridLayout.addWidget(self.pbCancelInvoice, 1, 3, 1, 1)

        self.retranslateUi(Invoice)
        QtCore.QMetaObject.connectSlotsByName(Invoice)

    def retranslateUi(self, Invoice):
        _translate = QtCore.QCoreApplication.translate
        Invoice.setWindowTitle(_translate("Invoice", "Form"))
        self.label.setText(_translate("Invoice", "Amount:"))
        self.pbInvoice.setText(_translate("Invoice", "Create Invoice"))
        self.pbCancelInvoice.setText(_translate("Invoice", "Cancel"))
