# Form implementation generated from reading ui file 'ui\pay.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Pay(object):
    def setupUi(self, Pay):
        Pay.setObjectName("Pay")
        Pay.resize(400, 69)
        self.gridLayout = QtWidgets.QGridLayout(Pay)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Pay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.txtPayRequest = QtWidgets.QLineEdit(Pay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtPayRequest.sizePolicy().hasHeightForWidth())
        self.txtPayRequest.setSizePolicy(sizePolicy)
        self.txtPayRequest.setText("")
        self.txtPayRequest.setPlaceholderText("")
        self.txtPayRequest.setObjectName("txtPayRequest")
        self.gridLayout.addWidget(self.txtPayRequest, 0, 1, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(186, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 2)
        self.pbPay = QtWidgets.QPushButton(Pay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbPay.sizePolicy().hasHeightForWidth())
        self.pbPay.setSizePolicy(sizePolicy)
        self.pbPay.setObjectName("pbPay")
        self.gridLayout.addWidget(self.pbPay, 1, 2, 1, 1)
        self.pbCancelPay = QtWidgets.QPushButton(Pay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbCancelPay.sizePolicy().hasHeightForWidth())
        self.pbCancelPay.setSizePolicy(sizePolicy)
        self.pbCancelPay.setObjectName("pbCancelPay")
        self.gridLayout.addWidget(self.pbCancelPay, 1, 3, 1, 1)

        self.retranslateUi(Pay)
        QtCore.QMetaObject.connectSlotsByName(Pay)

    def retranslateUi(self, Pay):
        _translate = QtCore.QCoreApplication.translate
        Pay.setWindowTitle(_translate("Pay", "Form"))
        self.label.setText(_translate("Pay", "Payment request:"))
        self.pbPay.setText(_translate("Pay", "Pay"))
        self.pbCancelPay.setText(_translate("Pay", "Cancel"))
