# Form implementation generated from reading ui file 'ui\unlock.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Unlock(object):
    def setupUi(self, Unlock):
        Unlock.setObjectName("Unlock")
        Unlock.resize(259, 69)
        self.gridLayout = QtWidgets.QGridLayout(Unlock)
        self.gridLayout.setObjectName("gridLayout")
        self.txtPasswordUnlock = QtWidgets.QLineEdit(Unlock)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtPasswordUnlock.sizePolicy().hasHeightForWidth())
        self.txtPasswordUnlock.setSizePolicy(sizePolicy)
        self.txtPasswordUnlock.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtPasswordUnlock.setObjectName("txtPasswordUnlock")
        self.gridLayout.addWidget(self.txtPasswordUnlock, 0, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(157, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.pbUnlock = QtWidgets.QPushButton(Unlock)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbUnlock.sizePolicy().hasHeightForWidth())
        self.pbUnlock.setSizePolicy(sizePolicy)
        self.pbUnlock.setObjectName("pbUnlock")
        self.gridLayout.addWidget(self.pbUnlock, 1, 1, 1, 1)

        self.retranslateUi(Unlock)
        QtCore.QMetaObject.connectSlotsByName(Unlock)

    def retranslateUi(self, Unlock):
        _translate = QtCore.QCoreApplication.translate
        Unlock.setWindowTitle(_translate("Unlock", "Form"))
        self.txtPasswordUnlock.setText(_translate("Unlock", "Santiago1"))
        self.txtPasswordUnlock.setPlaceholderText(_translate("Unlock", "Password..."))
        self.pbUnlock.setText(_translate("Unlock", "Unlock"))
